### ISSUE TITLE
Do we need an API?

### ISSUE THREAD

**Issue by skx** [skx/puppet-summary#17]
I wrote a couple of endpoints:

* `/api/state/XXX`
   * Return a JSON array of hosts in the give state (`failed`, `changed`, `unchanged`).
* `/api/nodes/(pattern)`
   * Return all known node hostnames.
   * Optionally all that match the supplied pattern (as a regular-expression)

Not sure if it is useful enough to add on its own?

When I do this kind of thing at work I want to export data based on the local system.  (i.e. "Nodes with package `bash`, or nodes with package `foo` version `bar`.)  That's hard to do without adding a specific module to collect that data - such that it ends up in the YAML report(s).

**Comment by stahnma** [comment]
Normally, I'd expect to get that data (e.g. package data) from PuppetDB via pql. The state data though seems useful.

**Comment by skx** [comment]
That's probably a fair response.  I use the locally archived facts, rather than puppetdb, so I think I'll just close this now we can call:

* https://master.steve.org.uk/api/state/changed
* https://master.steve.org.uk/api/state/failed
* https://master.steve.org.uk/api/state/unchanged

**Comment by stahnma** [comment]
You might want to keep it open to remind you (or me) to add those API endpoints to the README.

**Comment by skx** [comment]
(Added into `HACKING.md`).
