### ISSUE TITLE
Feature requests welcome!

### ISSUE THREAD

**Issue by skx** [skx/puppet-summary#20]
For my own personal needs I think this project is pretty much done.

* There might be bugs, which will be fixed.
* There might be improvements to the code-quality, test-cases, and coverage, but from an end-user perspective these are internal details which don't matter.

Right now I can [view my nodes](https://master.steve.org.uk/), I can see their states, and I can look at what changed/failed.  That's pretty much all I wanted.   Compared to the original puppet-dashboard there are two notable omissions:

* We don't show "orphaned nodes".
  * i.e. Nodes that used to report in the past, but no longer do so.
  * In fact we explicitly prune reports with the expectation that nodes which no longer report will silently fall off the display.
* We don't show unchanged resources.
   * i.e. We show "changed", "failed", and "skipped" resources in the report-view, but not those that were OK.
   * I think that provides a less cluttered display, and is a good thing.  But I can see an argument for including the details. 

If I'm missing anything I'd be happy to hear though.

**Comment by soerenbe** [comment]
Hi Skx,
thanks for this piece of software. I was looking for something like that to replace my puppet-dashboard for exactly your reasons. I currently have it running for out 150 Nodes.

Following things I would find very useful: 

**Dashboard View**
I have a big Screen in my office. I think the puppet-dashboard hat such a view.

**A Summary API**
For me it doesn't matter what kind of API. I just want something to Plugin my Icinga. :)

It can be something like a commandline interface './puppet-summary status' or a web API 'http://localhost/api'


I think I also found some bug. But I think its better to open a case for each bug.

Best Regards
Sören

**Comment by skx** [comment]
A dashboard view, like puppet-dashboard, I can add.

An API could be added.  Right now there is just a simple way of getting nodes in a given state:

* [/api/state/changed](https://master.steve.org.uk/api/state/changed)
* [/api/state/unchanged](https://master.steve.org.uk/api/state/unchanged)
 
I assume something like:

* `/api/overview`
   * Return a JSON array of hashes.
   * Hash would contain `fqdn`, `state`, and `updated_at`.

Would that suffice?

As for bugs, please do report as separate issues :)

**Comment by soerenbe** [comment]
Oh. Ok. 

* /api/state/changed
* /api/state/unchanged
* /api/state/failed

This is already fine for me. Great! So its just a documentation issue to find this URLs. :)

With this data I also can build a Dashboard for our infrstructure. So a special puppet-summary-dashboard is not really required for me. But maybe for other people.

**Comment by skx** [comment]
OK that's good, thanks for your prompt update.

Those end-points are documented in the `HACKING.md` file, but perhaps that could be moved.   I still think a dashboard view would still be nice, but I'll wait a bit longer before I work on it.
