### ISSUE TITLE
favicon?

### ISSUE THREAD

**Issue by stahnma** [skx/puppet-summary#30]
When I have lots of tabs open, it's hard to tell which one is the puppet-summary tab. Perhaps it needs a favicon so it can be noticeable in my seas of browser tabs.

**Comment by skx** [comment]
Yup that definitely can't hurt.

I was [inspired by this issue](https://github.com/sodabrew/puppet-dashboard/issues/343) to make sure every page has a unique title, but a favicon can't hurt.
