### ISSUE TITLE
Node Search?

### ISSUE THREAD

**Issue by picardrulez** [skx/puppet-summary#37]
I'm looking for a replacement for puppet dashboard and was playing with the live example of puppet-summary.  Is there any way to search for nodes using puppet-summary?

**Comment by skx** [comment]
I'm not sure how that would work.

Right now you can see the list of nodes on the interface - and you can get that data programmatically too, via [the API](https://github.com/skx/puppet-summary/blob/master/API.md) for example:

      $ curl -H Accept:application/json  https://master.steve.org.uk/

Other formats are available, and XML is particularly easy to parse too.  For example finding all nodes with "steve" in their name:

       $ curl -H Accept:application/xml  https://master.steve.org.uk/ | grep Fqd | grep steve
       <Fqdn>builder.steve.org.uk</Fqdn>
       <Fqdn>git.steve.org.uk</Fqdn>
       <Fqdn>master.steve.org.uk</Fqdn>
       <Fqdn>ssh.steve.org.uk</Fqdn>
       <Fqdn>www.steve.org.uk</Fqdn>

Does that help at all?  Or did you have something different in mind?

**Comment by picardrulez** [comment]
On puppet dashboard it has a node search where basically you can type in a portion of a hostname and it'll return a list of nodes that match, and from there you can click on your node and pull up the history of puppet runs.  Our puppet master is managing around 500 systems so the admins on our team regularly have to use the search feature to pull up node history.  If you wouldn't mind pointing me towards the portion of the code that builds the page I might be able to add something myself.

**Comment by skx** [comment]
It's been a while, but now I understand what you mean.

* Please visit https://master.steve.org.uk/
* On the front-page you'll find a search-box in the right hand side.
* Enter "vlan".  Press Return.

Does that match what you're looking for?  If so I'll tidy it up and get it ready later today/tomorrow. 

**NOTE**: Search page is only present on the index-page, to cut down time if I've got this wrong.

**Comment by skx** [comment]
Also note - I do a substring test.  Regular expression would be possible too.  Not sure which would be preferable.

**Comment by picardrulez** [comment]
Sounds exactly what I'm looking for!  I'm not seeing a search box on that link though.

**Comment by skx** [comment]
Top-right, in the header..

**Comment by picardrulez** [comment]
I'm out on my phone right now but this is what the top right looks like for me on that landing page.  I remember it looking the same on my desktop but ill double check again when I get home.

https://drive.google.com/file/d/0B-HbGUXRom7aVV9qQzJ3SnQ0dzg/view?usp=drivesdk

**Comment by skx** [comment]
Ahh that's annoying.  Can confirm the same happens to me on mobile.  On desktop it works fine.  I'll experiment with more bootstrap tweaks.

**Comment by skx** [comment]
Fixed now, I think :)

**Comment by picardrulez** [comment]
Awesome thanks!  Ill recompile when I get home and check it out
