### ISSUE TITLE
Working with musl?

### ISSUE THREAD

**Issue by stahnma** [skx/puppet-summary#43]
This is more of a question than an issue, but have you tried getting this to work with either musl or a `from scratch` docker build? I get odd error like "file not found" when working with anything not glibc backed. It could be because of libraries in play here (probably is), but I'm not sure. Basically, I wanted a very tiny container to run this from. I can make it work with something like Ubuntu, but that's 128MB container. I was hoping for something < 5. 

I'll keep fiddling with it, but figured I put a note here to see if anybody else had success here.

**Comment by skx** [comment]
I'm sorry to say no.

I've never tried deploying this application under docker, nor have I used any combination of musl + golang.

If there are changes I can make to allow this to work I'd be happy to make them, but I'd rely upon you/others to tell me what was necessary :)
