### ISSUE TITLE
Graph timestamp in node view

### ISSUE THREAD

**Issue by matejzero** [skx/puppet-summary#45]
Hello,

I was debuging a high runtime today and noticed I can't get a timestamp from the graph or table below.  My only option was to count dots and locate the run in table below.

I think this feature could be useful for such cases if it's not too much trouble to implement.

**Comment by skx** [comment]
Just so we're clear:

* You're looking at a single node.
* You see a graph of run-time.
* But you cannot get the actual run-time from it, and it isn't displayed in the table so you don't know how long things took.

Is that correct?

Picking an example of one of my hosts `blogspam.blogspam.net` I see the recent-runs here:

* https://master.steve.org.uk/node/blogspam.blogspam.net

There I see the timestamp, and if I hover my mouse it shows the run-time, in seconds:

![time](https://user-images.githubusercontent.com/735291/37822101-2cfbc700-2e8e-11e8-8c09-d1d878cde032.jpg)

Are you saying you __don't__ see the time, when you hover?  (Or possibly that you didn't know you could?)

**Comment by matejzero** [comment]
(I should start working on writing more clear issues:) ).

You are right about the node view.

As far as time goes, while you are hovering over the graph, you see number of dots and run-time in seconds, but it's hard to connect that dot to a report in the table. 

Now that I think of it, it might be better to have a column with numbers that corresponds to numbers in graph with numbers from 50 to 1 (I take it far left is the oldest report).

|ID|Node|Status|Seen|Failed|Changed|
|--|--|--|--|--|--|
|50|blogspam|unchanged|1 hour ago|0|0|
|49|blogspam|unchanged|2 hour ago|0|0|

**Comment by skx** [comment]
Great, so I understand now:

* You can see the timestamps.
* But you can't link that to a specific run.

I did, in the past, have a timestamp field in the table but decided I didn't want to keep it as it was often a long number ("2.389382seconds") which looked ugly.

I will do two things to fix this issue:

* I will add the run-time to the report-page.
  * That will ensure you can see it and confirm it is OK when using the ID.
* I will add an ID which corresponds to the reports 
  * As you suggest

That probably needs a sanity-check to make sure the numbers are ascending/descending appropriately.

**Comment by matejzero** [comment]
Yea, the biggest problem is linking table records with graph values.

As far as long run-time goes, I guess you could truncate it and only show seconds as I think that should be enough.

Do you think 'id' numbers in graph should be reversed? So we start our table ID with 1 at the top?

**Comment by skx** [comment]
I just wanted to check that the graph goes left->right (1->N) matches the table view, so that ID 1 is the right report.

I'll soon find out :)

**Comment by skx** [comment]
I think this is fixed now; I've updated my master.  You should be able to clearly find report-ID 48 which is the slow one - and confirm that because the run-time is listed on the report-page:

* https://master.steve.org.uk/node/builder.steve.org.uk

Please let me know if that suits you?

**Comment by matejzero** [comment]
Wonderful! This is exactly what I was looking for:)

**Comment by skx** [comment]
Great, thanks for the swift update.

(Some things, like this issue, are obvious when they're pointed out but they would never have occurred to me!)

**Comment by matejzero** [comment]
Yea I know. Different user base / scale / needs.

Thank you too for quick update:)
