### ISSUE TITLE
Pruning does not appear to be working

### ISSUE THREAD

**Issue by picardrulez** [skx/puppet-summary#48]
When I run the following command:
puppet-summary prune -days 7 -prefix /mnt/puppetSummary/reports
The command returns immediately with no pruning actually occurring.

**Comment by skx** [comment]
* Do you have entries older than seven days, stored on disk, or in the database?
* Do you see anything useful if you add `-verbose` ?

**Comment by picardrulez** [comment]
Yeah I had entries all the way back to June 4th, even though the cron's been running every night.  I ended up removing anything older than 7 days manually.  I'll run it with verbose tomorrow when we've got older files and I'll send you the output

**Comment by skx** [comment]
OK great - bear in mind that the database is the source of truth when it comes to reports & history.  If you have sqlite3 installed you could run this:

     $ sqlite3  ps.db 
     > SELECT id,yaml_file FROM reports WHERE ( ( strftime('%s','now') - executed_at ) > ( 60 * 60 * 24 * 8 ));

That'll show reports older than 8 days.  Adjust appropriately.

**Comment by picardrulez** [comment]
Just ran that sqlite statement.  It returned the thousands of reports I manually deleted the files for yesterday.  I just ran the prune command again with the verbose option and it returned "Removing" followed by the ID and disk location of all the thousands of reports.  A subsequent run of the command shows that there's nothing more to remove.  Extremely strange but it appears to have worked now.  I'll close the issue ticket.

**Comment by picardrulez** [comment]
Hey I think I tracked down the cause of the issue.  It appears it wasn't actually working as a cron because I was giving the full path of the puppet-summary binary and not actually executing it in the same directory (so puppet-summary wasn't finding it's db file).  Would it be possible to get puppet-summary to give an error if it attempts to prune and can't find the db file, and also would it be possible to get a puppet-summary option to specify the working directory, or maybe even just specify the location of the db file to make it easier to put in a cron?  I'm about to just make bash wrapper to put in cron to ensure I cd into the correct directory before pruning, but I'd feel a lot better if I didn't have to wrap it for the cron.

**Comment by skx** [comment]
> or maybe even just specify the location of the db file to make it easier to put in a cron?

You can already specify the path to the database you expect:

      puppet-summary prune -db-file /path/to/ps.db -verbose 

That's documented in the very last section of the README.md file, though I appreciate it could be more explicit.

**Comment by picardrulez** [comment]
Perfect! thanks!
