### ISSUE TITLE
Do not depend on external sites

### ISSUE THREAD

**Issue by nono-gdv** [skx/puppet-summary#67]
Hello,

Currently several URLs under https://maxcdn.bootstrapcdn.com/, https://code.jquery.com/ and https://cdnjs.cloudflare.com/ are hardcoded in the templates. Would it be possible to expose these URLs are configuration options rather than depending on third parties?

**Comment by skx** [comment]
I can appreciate some people might prefer to avoid using those locations, but I'd be a little concerned that adding three new configuration options is a bit much for such a simple project.

I think the better approach would be to embed the resources in the binary, that way users don't need an external service and I don't need to deal with a potentially growing list of configuration flags.

(I _already_ do that for `/jquery.tablesorter.min.js`, though I'd want to make the way that is served more general; probably adding a "404-handler" which will detect requests to routes that are unknown and serve embedded resources if they can be handled that way.)

Does that seem like a good compromise for you?

**Comment by nono-gdv** [comment]
Yes, that would be perfect!

**Comment by skx** [comment]
Fixed in #68, available in [release-1.6](https://github.com/skx/puppet-summary/releases/tag/release-1.6)
