### ISSUE TITLE
max limit on node report display is 50?

### ISSUE THREAD

**Issue by corporate-gadfly** [skx/puppet-summary#74]
I have a node with 400+ YAML reports in the `reports` directory. But only 50 show up in the UI.

Is there a limit of 50 somewhere in code?

**Comment by corporate-gadfly** [comment]
I see the [LIMIT 50](https://github.com/skx/puppet-summary/blob/cc02b09bef5ed2f08f4d3f75347e742d427f31b4/db.go#L592) clause in the SQL statement.

Any plans to make it configurable?

**Comment by skx** [comment]
I'd forgotten all about this limit,  it in a previous role we had puppet running every 30 minutes which meant for a node 7 days would have:

* `24 * 2 * 7` = 300+ reports

It seemed sensible to only concentrate on the most recent.  To be honest I suspect a limit of 500 is as sane, and it might even be there should be no limit..

**Comment by skx** [comment]
Available now:

* https://github.com/skx/puppet-summary/releases/tag/release-1.8
