### ISSUE TITLE
search results are not sortable

### ISSUE THREAD

**Issue by corporate-gadfly** [skx/puppet-summary#79]
Happy new year!

A (somewhat) minor request about search results.

After entering a search term, the results are displayed in a table with following headers:

- Node
- State
- Seen

However, unlike the rest of the screens, the heading row is not clickable, making the results non-sortable.

**Comment by skx** [comment]
Thanks for the report!  I'm not using puppet any longer, but I should be able to resolve this in the next week or two.

Mostly it'll mean copying the javascript magic from `data/index.template` to `data/results.template`, at least:

* The inclusion of `jquery.tablesorter.min.js`
* The invocation `$('#all_table').tablesorter();`

Once that's done I think just regenerating the embedded resources, with `implant`, and rebuilding will suffice.  Nothing else jumps out as being required - but I admit I've not looked too carefully.

**Comment by skx** [comment]
Released

* https://github.com/skx/puppet-summary/releases/tag/release-1.10

**Comment by corporate-gadfly** [comment]
Confirmed, TY. And thanks for your time and efforts in the past.
