### ISSUE TITLE
Improve build instructions

### ISSUE THREAD

**Issue by larsen0815** [skx/puppet-summary#87]
For go newbies like me, it should be made more clear where the binary is installed.

I installed go via ````apt install golang```` on my Debian Bookworm VM. Then ran ````go install```` in the directory where I cloned the git repository (/opt/puppet-summary), and expected the binary to be created there. As apparently nothing happened (no output, no binary), I downloaded the binary instead.

It's only now that I tried out "stuff from the internet" (TM), that I noticed the binary is installed to ````/root/go/bin/````.

**Comment by skx** [comment]
I guess this wouldn't hurt, for sure.  

Generally "go install" will always install to the go-binary directory, which you could find by running "go env".  Look for the "GOPATH" value, and add "bin/" to the end.
