### ISSUE TITLE
How to listen on any IP address

### ISSUE THREAD

**Issue by larsen0815** [skx/puppet-summary#88]
As I restrict access to the server with a firewall, and don't want to use a reverse proxy, but still want to use localhost on the server itself instead of the IP that might change, I need puppet-summary to listen on any IP address. Found out this is possible by specifying an empty string as host:

````
# /opt/puppet-summary/puppet-summary serve -host ""
Launching the server on http://:3001
````

Would be nice to have this documented =)

**Comment by larsen0815** [comment]
Or use ````-host 0.0.0.0````

**Comment by skx** [comment]
If you wanted to update the README to include that I'd be happy to accept the change :)

**Comment by skx** [comment]
Thanks for your pull-request, applied now :)
