### ISSUE TITLE
systemd service file

### ISSUE THREAD

**Issue by larsen0815** [skx/puppet-summary#89]
To have puppet-summary start as a daemon:

````
cd /etc/systemd/system

cat <<EOF > puppet-summary.service
[Unit]
Description=Web interface providing reporting features for Puppet
[Service]
Type=simple
WorkingDirectory=/opt/puppet-summary
ExecStart=/opt/puppet-summary/puppet-summary serve -auto-prune -host 0.0.0.0
[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload && \
systemctl enable --now puppet-summary.service && \
systemctl status puppet-summary.service
````

Will listen on any IP.
Adapt path to your installation directory.

**Comment by skx** [comment]
I'd be happy to include that in a "samples/" directory, if you wanted to submit a pull-request.

**Comment by larsen0815** [comment]
Please delete merge request #91

**Comment by skx** [comment]
Thanks for your merge-request, applied now :)

**Comment by larsen0815** [comment]
Could you please delete merge request https://github.com/skx/puppet-summary/pull/91?
